In [1]:
import torch
x=torch.arange(4.0)

In [2]:
x

tensor([0., 1., 2., 3.])

In [3]:
# 储存梯度

x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [4]:
x.grad

In [10]:
y=torch.dot(x,x)
y=x**5
y

tensor([  0.,   1.,  32., 243.], grad_fn=<PowBackward0>)

这里的14指的是点积后得到的运算结果：0*0+1*1+2*2+3*3=14

接下来**通过调用反向传播函数来自动计算y关于x每个分量的梯度**

In [11]:
y.backward()
x.grad

RuntimeError: grad can be implicitly created only for scalar outputs

In [15]:
x.grad==2*x
print(2*x)

tensor([0., 2., 4., 6.], grad_fn=<MulBackward0>)
